# Generated by Django 5.0.7 on 2024-08-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productoffer_created_at_productoffer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoffer',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
