# Generated by Django 5.0.7 on 2024-08-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_offerproductnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproductnews',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
