# Generated by Django 5.0.7 on 2024-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_offerproductnews_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='short_description',
            field=models.CharField(default='dfdfd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuredproduct',
            name='title',
            field=models.CharField(default='fdsdf', max_length=25),
            preserve_default=False,
        ),
    ]
