# Generated by Django 5.0.7 on 2024-08-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_featuredproduct_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank='', max_length=20, null=True),
        ),
    ]
