# Generated by Django 5.0.7 on 2024-09-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productlog_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='action',
            field=models.CharField(choices=[('delete', 'Delete'), ('update', 'Update'), ('create', 'Create'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
